### ISSUE TITLE
kernel panic

### ISSUE THREAD

**Issue by riflexpuma** [TECHNIKVERBOT/Dell-Precision-7520-OpenCore#2]
I have the exact same setup as you. With ventura 13.3 kernel panic. I used the first EFI skylake without amd. could you tell me why? I don't know. Thank you

![Immagine WhatsApp 2023-04-01 ore 09 15 02](https://user-images.githubusercontent.com/127793258/229271795-ca7469b0-b133-4cd4-b781-6e2eb50a7d4e.jpg)

**Comment by DavidCGranger** [comment]
Sorry for the late reply, our testing machine died. If you still want to do it, you have to use the EFI you get when you clone the repo, not the one from releases, since that one is quite outdated.
